[package]
name = "privacy-vs-compliance"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
rand = "0.8"

halo2_proofs = { version = "0.3", default-features = false, features = ["curves"] }
halo2_gadgets = "0.3"
pasta_curves = "0.5"

[dev-dependencies]
# np. proptest = "1.4"
